### ISSUE TITLE
Filter bug when preforming a search

### ISSUE THREAD

**Issue by RyanNoelk** [RyanNoelk/OpenEats#204]
Getting some weird issues with the filters not updating correctly when performing a search.

**Comment by DJCrashdummy** [comment]
i'm not sure if we are really talking about the same issues, but i guess they are at least related:

- the course filter does not work (correct)
![1](https://user-images.githubusercontent.com/26110463/27878775-9f9750be-61bf-11e7-9eac-6af6aae0dc0c.png)

- and when entering more than one word into the text filter all other filters are "gone"...
![2](https://user-images.githubusercontent.com/26110463/27878824-d352881a-61bf-11e7-97b4-cbdc80a78f89.png)

**Comment by RyanNoelk** [comment]
Yep, same issue.

**Comment by RyanNoelk** [comment]
This issues is fixed in #211 .

**Comment by DJCrashdummy** [comment]
there is still a filter-bug, but now the rating-filter gets strange (numbers are too high - course- & cuisine-numbers are correct):

![open_eats](https://user-images.githubusercontent.com/26110463/28674917-9a4394dc-72e6-11e7-8daf-3141039879d0.png)

**Comment by DJCrashdummy** [comment]
AND the second bug mentioned in my first comment https://github.com/RyanNoelk/OpenEats/issues/204#issuecomment-313186818 still persists.

**Comment by RyanNoelk** [comment]
I should have a fix for both of these issues. Waiting for the CI to run and then I'll merge it :)

**Comment by RyanNoelk** [comment]
The filters should be working now. Please reopen this if they are not.
